default:
  collection: ncs_loveandseduction
  solr_core: ncs_loveandseduction
  tei_solr_xsl: scripts/solr_transform_tei.xsl
  threads: 20
development:
  solr_path: https://cdrhdev1.unl.edu/solr
production:
  solr_path: https://cors1601.unl.edu/solr
